const BestIMDbArr = [
  // Fight Club
  {
    id: 34,
    url: "/./images/imdb/fight-club.webp",
    name: "Fight Club",
    year: "۱۹۹۹",
    category: "فیلم",
    image1: "/../images/D-IMDB/fightclub1.webp",
    image2: "/../images/D-IMDB/fightclub2.webp",
    image3: "/../images/D-IMDB/fightclub3.webp",
    age: "+۱۶",
    time: "۲:۱۹:۰۰",
    rate: "۸۹٪",
    bgImg: "../images/D-IMDB/fightclub.webp",
    description:
      "شخصیت اصلی فیلم جوان بی‌نامی است که به عنوان راوی شناخته می‌شود. راوی زندگی غیرعادی و عجیبی دارد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // The Dark Knight
  {
    id: 35,
    url: "/./images/imdb/dark-knight.webp",
    name: "The Dark Knight",
    year: "۲۰۰۸",
    category: "فیلم",
    image1: "/../images/D-IMDB/dark-knight1.webp",
    image2: "/../images/D-IMDB/dark-knight2.webp",
    image3: "/../images/D-IMDB/dark-knight3.webp",
    age: "+۱۶",
    time: "۲:۳۲:۰۰",
    rate: "۹۰٪",
    bgImg: "../images/D-IMDB/dark-knight.webp",
    description:
      "در گاتهام سیتی، یک سال پس از ناپدید شدن دکتر جاناتان کرین معروف به مترسک، امنیت توسط بتمن دوباره به گاتهام بازگردانده شده.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Breaking Bad
  {
    id: 36,
    url: "/./images/imdb/breaking-bad.webp",
    name: "Breaking Bad",
    year: "۲۰۰۸",
    category: "سریال",
    image1: "/../images/D-IMDB/breaking-bad1.webp",
    image2: "/../images/D-IMDB/breaking-bad2.webp",
    image3: "/../images/D-IMDB/breaking-bad3.webp",
    age: "+۱۶",
    time: "۴۵:۰۰",
    rate: "۹۷٪",
    bgImg: "../images/D-IMDB/breaking-bad.webp",
    description:
      "بریکینگ بد داستان والتر وایت دانشمند شیمی زحمتکش و بی‌حاشیه‌ای را به تصویر می‌کشد که دبیر دبیرستان است. وایت در ابتدای داستان متوجه می‌شود که مبتلا به سرطان ریه است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Inception
  {
    id: 37,
    url: "/./images/imdb/inception.webp",
    name: "Inception",
    year: "۲۰۱۰",
    category: "فیلم",
    image1: "/../images/D-IMDB/inception1.webp",
    image2: "/../images/D-IMDB/inception2.webp",
    image3: "/../images/D-IMDB/inception3.webp",
    age: "+۳",
    time: "۲:۲۸:۰۰",
    rate: "۸۳٪",
    bgImg: "../images/D-IMDB/inception.webp",
    description:
      "دام کاب (لئوناردو دی‌کاپریو) یک دزد ماهر در استخراج اسرار ارزشمند مورد نیاز سازمان‌های جاسوسی و شرکت‌های تجاری و چندملیتی است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // La La Land
  {
    id: 38,
    url: "/./images/imdb/lala-land.webp",
    name: "La La Land",
    year: "۲۰۱۶",
    category: "فیلم",
    image1: "/../images/D-IMDB/lalaland1.webp",
    image2: "/../images/D-IMDB/lalaland2.webp",
    image3: "/../images/D-IMDB/lalaland3.webp",
    age: "+۱۶",
    time: "۲:۰۸:۲۷",
    rate: "۷۹٪",
    bgImg: "../images/D-IMDB/lalaland.webp",
    description:
      "میا، دختری جوان و مشتاقِ بازیگری است که در کافی‌شاپ کمپانی برادران وارنر مشغول به کار است و در فاصله‌ی آزمون‌های بازیگری خود به بازیگرهای هالیوود قهوه لاته می‌دهد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Coda
  {
    id: 39,
    url: "/./images/imdb/coda.webp",
    name: "Coda",
    year: "۲۰۲۱",
    category: "فیلم",
    image1: "/../images/D-IMDB/coda1.webp",
    image2: "/../images/D-IMDB/coda2.webp",
    image3: "/../images/D-IMDB/coda3.webp",
    age: "+۱۳",
    time: "۱:۵۵:۰۰",
    rate: "۶۹٪",
    bgImg: "../images/D-IMDB/codaa.webp",
    description:
      "داستان فیلم در مورد دختری جوان به نام روبی است که تنها عضو شنوای خانواده است. پدر، مادر و برادر بزرگتر روبی به نام لئو همگی ناشنوا هستند.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Interstellar
  {
    id: 40,
    url: "/./images/imdb/interstellar.webp",
    name: "Interstellar",
    year: "۲۰۱۴",
    category: "فیلم",
    image1: "/../images/D-IMDB/interstellar1.webp",
    image2: "/../images/D-IMDB/interstellar2.webp",
    image3: "/../images/D-IMDB/interstellar3.webp",
    age: "+۱۳",
    time: "۲:۴۹:۵۶",
    rate: "۹۱٪",
    bgImg: "../images/D-IMDB/interstellarpng.webp",
    description:
      "در آینده زمین به علت آتشک محصولات کشاورزی رو به نابودی است و هر روز محصولات بیشتری نابود می‌شود. متیو به همراه پدر زن، پسر و دخترش در یک مزرعه زندگی می‌کنند.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // The Godfather
  {
    id: 41,
    url: "/./images/imdb/god-father.webp",
    name: "The Godfather",
    year: "۱۹۷۲",
    category: "فیلم",
    image1: "/../images/D-IMDB/god1.webp",
    image2: "/../images/D-IMDB/god2.webp",
    image3: "/../images/D-IMDB/god3.webp",
    age: "+۱۵",
    time: "۲:۵۵:۰۰",
    rate: "۸۹٪",
    bgImg: "../images/D-IMDB/the-godfather.webp",
    description:
      "فیلم در جشن عروسی کانی، دختر دون ویتو کورلئونه، با کارلو ریزی در لانگ بیچ نیویورک، لانگ آیلند در اواخر تابستان ۱۹۴۵ شروع می‌شود.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
];

export default BestIMDbArr;
