const AnimationsArr = [
  // Sponge Bob
  {
    id: 21,
    url: "/../images/animation/sponge-bob.webp",
    name: "باب اسنفجی",
    year: "۱۹۹۹",
    category: "انیمیشن",
    bgImg: "../images/animation/pong-bob.webp",
    image1: "/../images/D-Animation/bob1.webp",
    image2: "/../images/D-Animation/bob2.webp",
    image3: "/../images/D-Animation/bob3.webp",
    age: "+۳",
    time: "۳۸:۰۰",
    rate: "۱۰۰٪",
    description:
      "شخصیت اصلی کارتون باب اسفنجی شلوار مکعبی است که در یک رستوران آشپز است و به کار نسبتاً ساده و یکنواخت خود بسیار علاقه‌مند است و به گل لاله حساسیت دارد ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Panda
  {
    id: 22,
    url: "/./images/animation/panda.svg",
    name: "پاندای کونگ فو کار ۳",
    year: "۲۰۱۶",
    category: "انیمیشن",
    bgImg: "../images/animation/panda.svg",
    image1: "/../images/D-Animation/panda1.jpg",
    image2: "/../images/D-Animation/panda2.jpg",
    image3: "/../images/D-Animation/panda3.jpg",
    age: "+۳",
    time: "۳۰:۰۰",
    rate: "۹۵٪",
    description:
      "داستان این انیمیشن در چین باستان رخ می‌دهد؛ پاندای چاق بی دست و پایی به نام پو که به توانایی های خود آگاه نیست ولی علاقه زیادی به کونگ فو دارد ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Ice Age
  {
    id: 23,
    url: "/./images/animation/ice-age.webp",
    name: "عصر یخبندان",
    year: "۲۰۰۲",
    category: "انیمیشن",
    bgImg: "../images/animation/ice-age.webp",
    image1: "/../images/D-Animation/asr1.webp",
    image2: "/../images/D-Animation/asr2.webp",
    image3: "/../images/D-Animation/asr3.webp",
    age: "+۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۹۸٪",
    description:
      "ابتدا حمله‌ای توسط گروهی از ببرهای دندان خنجری به یکی از دهکده‌های انسان‌ها صورت می‌گیرد که طی آن همسر یکی از افراد قبیله  ... ",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Cars
  {
    id: 24,
    url: "/./images/animation/cars.webp",
    name: "ماشین‌ها",
    year: "۲۰۰۶",
    category: "انیمیشن",
    bgImg: "../images/animation/cars2.webp",
    image1: "/../images/D-Animation/cars1.webp",
    image2: "/../images/D-Animation/cars2.webp",
    image3: "/../images/D-Animation/cars3.jpg",
    age: "+۳",
    time: "۱:۵۸:۰۰",
    rate: "۹۸٪",
    description:
      "لایتنینگ مک کوئین ماشین مسابقه تازه‌کاری است که تنها هدفش برنده شدن است به‌طوری‌که برای برنده شدن اخلاق‌های خود را زیر پا می‌گذارد. در یک روز ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Tom & Jerry
  {
    id: 25,
    url: "/./images/animation/tom&jerry.webp",
    name: "تام و جری",
    year: "۱۹۴۰",
    category: "انیمیشن",
    bgImg: "../images/animation/tom&jerry.webp",
    image1: "/../images/D-Animation/tom1.jpg",
    image2: "/../images/D-Animation/tom2.jpg",
    image3: "/../images/D-Animation/tom3.jpg",
    age: "+۳",
    time: "۱۸:۰۰",
    rate: "۱۰۰٪",
    description:
      "این دو شخصیت با همدیگر دشمن اند ولی وقتی در یک دردسر بزرگی که بین آن دو می‌آید با هم متحد می‌شوند ولی شانس جری موشه بیش‌تر از تام گربه‌هه است ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Pink Panther
  {
    id: 26,
    url: "/./images/animation/pink-panther.webp",
    name: "پلنگ صورتی",
    year: "۱۹۶۹",
    category: "انیمیشن",
    bgImg: "../images/animation/pink.webp",
    image1: "/../images/D-Animation/pink1.jpg",
    image2: "/../images/D-Animation/pink2.png",
    image3: "/../images/D-Animation/pink3.jpg",
    age: "+۳",
    time: "۱۵:۰۰",
    rate: "۹۸٪",
    description:
      "پلنگ صورتی مجموعه فیلمهای کمدی-پلیسی است که اولین آن‌ها در سال ۱۹۶۳ ساخته شد و با موفقیت آن دنباله‌های زیادی برایش ساخته شد ... ",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Madagascar
  {
    id: 27,
    url: "/./images/animation/madagascar.webp",
    name: "ماداگاسکار ۲",
    year: "۲۰۰۵",
    category: "انیمیشن",
    bgImg: "../images/animation/madagascar1.webp",
    image1: "/../images/D-Animation/madagascar1.jpg",
    image2: "/../images/D-Animation/madagascar2.jpg",
    image3: "/../images/D-Animation/madagascar3.jpg",
    age: "+۳",
    time: "۱:۲۹:۰۰",
    rate: "۹۵٪",
    description:
      "الکس بچه‌ای بازیگوش بوده و پدرش هم سلطان جنگل. پدرش می‌خواهد او را برای جانشینی خود تربیت کند، ولی الکس فقط به دنبال بازی است. ناگهان ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Toy Story
  {
    id: 28,
    url: "/./images/animation/toy-story.webp",
    name: "داستان اسباب بازی",
    year: "۱۹۹۵",
    category: "انیمیشن",
    bgImg: "../images/animation/toy-story.webp",
    image1: "/../images/D-Animation/toy1.jpg",
    image2: "/../images/D-Animation/toy2.jpg",
    image3: "/../images/D-Animation/toy3.jpg",
    age: "+۳",
    time: "۱:۲۸:۰۰",
    rate: "۹۸٪",
    description:
      "در یک دنیایی که اسباب‌بازی‌ها در غیاب انسان‌ها زنده می‌شوند. گروهی از اسباب‌بازی‌ها درحال آماده شدن برای نقل مکان به یک خانه جدید به همراه صاحبشان ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Luca
  {
    id: 29,
    url: "/./images/animation/luca.webp",
    name: "لوکا",
    year: "۲۰۲۱",
    category: "انیمیشن",
    bgImg: "../images/animation/luca.webp",
    image1: "/../images/D-Animation/luca1.jpg",
    image2: "/../images/D-Animation/luca2.jpg",
    image3: "/../images/D-Animation/luca3.jpg",
    age: "+۳",
    time: "۱:۳۵:۰۰",
    rate: "۷۸٪",
    description:
      "کودک هیولای دریایی ترسو، لوکا پاگورو، از چند بزماهی در سواحل شهر پورتوروسو در ایتالیا نگهداری می‌کند. والدینش از ترس اینکه ممکن است توسط انسان‌ها شکار شود ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Soul
  {
    id: 30,
    url: "/./images/animation/soul1.webp",
    name: "روح",
    year: "۲۰۲۰",
    category: "انیمیشن",
    bgImg: "../images/animation/soul.webp",
    image1: "/../images/D-Animation/soul1.jpg",
    image2: "/../images/D-Animation/soul2.jpg",
    image3: "/../images/D-Animation/soul3.jpg",
    age: "+۳",
    time: "۲:۳۸:۰۰",
    rate: "۵۸٪",
    description:
      "داستان فیلم پویانمایی روح، دربارهٔ جو گاردنر، آموزگار نوازندگی یک گروه موسیقی در دبیرستان است. جو که همیشه سودای اجرای موسیقی جاز بر صحنه را در سر می‌پرورانده ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Rango
  {
    id: 31,
    url: "/./images/animation/rangopng.webp",
    name: "رنگو",
    year: "۲۰۱۱",
    category: "انیمیشن",
    bgImg: "../images/animation/rango.webp",
    image1: "/../images/D-Animation/rango1.jpg",
    image2: "/../images/D-Animation/rango2.jpg",
    image3: "/../images/D-Animation/rango3.jpg",
    age: "+۳",
    time: "۱:۴۷:۰۰",
    rate: "۸۸٪",
    description:
      "انیمیشن رنگو داستان زندگی یک آفتاب‌پرست (بزمجه) خانگی است که دچار بحران هویت می‌باشد. این فیلم که حال و هوایی وسترن و کمدی دارد ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Dolphin Boy
  {
    id: 32,
    url: "/./images/animation/dolphin.webp",
    name: "پسر دلفینی",
    year: "۲۰۲۱",
    category: "انیمیشن",
    bgImg: "../images/animation/dolphin1.webp",
    image1: "/../images/D-Animation/dolphin1.jpg",
    image2: "/../images/D-Animation/dolphin2.jpg",
    image3: "/../images/D-Animation/dolphin3.jpg",
    age: "+۳",
    time: "۱:۳۰:۰۰",
    rate: "۸۰٪",
    description:
      "هنگامی که یک هواپیما در دریا سقوط می کند، یک دلفین جوان به نام سفید و مادرش یک نوزاد انسانی پیدا می کنند و از او مراقبت می کنند. دلفین بعداً بزرگ می‌شود و ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Turning Red
  {
    id: 33,
    url: "/./images/animation/turning-red.webp",
    name: "قرمز شدن",
    year: "۲۰۲۱",
    category: "انیمیشن",
    bgImg: "../images/animation/turning-red1.webp",
    image1: "/../images/D-Animation/turning1.jpg",
    image2: "/../images/D-Animation/turning2.jpg",
    image3: "/../images/D-Animation/turning3.jpg",
    age: "+۳",
    time: "۱:۴۰:۰۰",
    rate: "۶۸٪",
    description:
      " میلین «می» لی، یک دانش‌آموز ۱۳ ساله چینی-کانادایی را دنبال می‌کند که به دلیل یک نفرین ارثی، وقتی هر احساس شدیدی را تجربه می‌کند، به یک ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
];
export default AnimationsArr;
