const AnimationsArr = [
  // Sponge Bob
  {
    id: 1,
    url: "../images/animation/sponge-bob.png",
    name: "باب اسنفجی",
    year: "۱۹۹۹",
    category: "انیمیشن",
    bgImg: "../images/animation/sponge-bob.png",
    image1: "../images/D-Animation/bob1.jpg",
    image2: "../images/D-Animation/bob2.jpg",
    image3: "../images/D-Animation/bob3.jpg",
    age: "+۳",
    time: "۳۸:۰۰",
    rate: "۱۰۰٪",
    description:
      "شخصیت اصلی کارتون باب اسفنجی شلوار مکعبی است که در یک رستوران آشپز است و به کار نسبتاً ساده و یکنواخت خود بسیار علاقه‌مند است و به گل لاله حساسیت دارد ...",
  },
  // Panda
  {
    id: 2,
    url: "./images/animation/panda.svg",
    name: "پاندای کونگ فو کار ۳",
    year: "۲۰۱۶",
    category: "انیمیشن",
    bgImg: "../images/animation/panda.svg",
    image1: "../images/D-Animation/panda1.jpg",
    image2: "../images/D-Animation/panda2.jpg",
    image3: "../images/D-Animation/panda3.jpg",
    age: "+۳",
    time: "۳۰:۰۰",
    rate: "۹۵٪",
    description:
      "داستان این انیمیشن در چین باستان رخ می‌دهد؛ پاندای چاق بی دست و پایی به نام پو که به توانایی های خود آگاه نیست ولی علاقه زیادی به کونگ فو دارد ...",
  },
  // Ice Age
  {
    id: 3,
    url: "./images/animation/ice-age.jpg",
    name: "عصر یخبندان",
    year: "۲۰۰۲",
    category: "انیمیشن",
    bgImg: "../images/animation/ice-age.jpg",
    image1: "../images/D-Animation/asr1.jpg",
    image2: "../images/D-Animation/asr2.jpg",
    image3: "../images/D-Animation/asr3.jpg",
    age: "+۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۹۸٪",
    description:
      "ابتدا حمله‌ای توسط گروهی از ببرهای دندان خنجری به یکی از دهکده‌های انسان‌ها صورت می‌گیرد که طی آن همسر یکی از افراد قبیله  ... ",
  },
  // Cars
  {
    id: 4,
    url: "./images/animation/cars.jpg",
    name: "ماشین‌ها",
    year: "۲۰۰۶",
    category: "انیمیشن",
    bgImg: "../images/animation/cars2.jpg",
    image1: "../images/D-Animation/cars1.jpg",
    image2: "../images/D-Animation/cars2.jpg",
    image3: "../images/D-Animation/cars3.jpg",
    age: "+۳",
    time: "۱:۵۸:۰۰",
    rate: "۹۸٪",
    description:
      "راحله به همراه خوانواده در یکی از محله‌های تهران زندگی می‌کنند. شوهر خواهر علی، فردی است که یک کسب و کار را برای خانم‌های محله ایجاد کرده است.",
  },
  // Tom & Jerry
  {
    id: 5,
    url: "./images/animation/tom&jerry.png",
    name: "تام و جری",
    year: "۱۹۴۰",
    category: "انیمیشن",
    bgImg: "../images/animation/tom&jerry.png",
    image1: "../images/D-Animation/tom1.jpg",
    image2: "../images/D-Animation/tom2.jpg",
    image3: "../images/D-Animation/tom3.jpg",
    age: "+۳",
    time: "۱۸:۰۰",
    rate: "۱۰۰٪",
    description:
      "این دو شخصیت با همدیگر دشمن اند ولی وقتی در یک دردسر بزرگی که بین آن دو می‌آید با هم متحد می‌شوند ولی شانس جری موشه بیش‌تر از تام گربه‌هه است ...",
  },
  // Pink Panther
  {
    id: 6,
    url: "./images/animation/pink-panther.png",
    name: "پلنگ صورتی",
    year: "۱۹۶۹",
    category: "انیمیشن",
    bgImg: "../images/animation/pink.jpg",
    image1: "../images/D-Animation/pink1.jpg",
    image2: "../images/D-Animation/pink2.png",
    image3: "../images/D-Animation/pink3.jpg",
    age: "+۳",
    time: "۱۵:۰۰",
    rate: "۹۸٪",
    description:
      "پلنگ صورتی مجموعه فیلمهای کمدی-پلیسی است که اولین آن‌ها در سال ۱۹۶۳ ساخته شد و با موفقیت آن دنباله‌های زیادی برایش ساخته شد ... ",
  },
  // Madagascar
  {
    id: 7,
    url: "./images/animation/madagascar.jpg",
    name: "ماداگاسکار ۲",
    year: "۲۰۰۵",
    category: "انیمیشن",
    bgImg: "../images/animation/madagascar1.jpg",
    image1: "../images/D-Animation/madagascar1.jpg",
    image2: "../images/D-Animation/madagascar2.jpg",
    image3: "../images/D-Animation/madagascar3.jpg",
    age: "+۳",
    time: "۱:۲۹:۰۰",
    rate: "۹۵٪",
    description:
      "الکس بچه‌ای بازیگوش بوده و پدرش هم سلطان جنگل. پدرش می‌خواهد او را برای جانشینی خود تربیت کند، ولی الکس فقط به دنبال بازی است. ناگهان ...",
  },
  // Toy Story
  {
    id: 8,
    url: "./images/animation/toy-story.jpeg",
    name: "داستان اسباب بازی",
    year: "۱۹۹۵",
    category: "انیمیشن",
    bgImg: "../images/animation/toy-story.jpeg",
    image1: "../images/D-Animation/toy1.jpg",
    image2: "../images/D-Animation/toy2.jpg",
    image3: "../images/D-Animation/toy3.jpg",
    age: "+۳",
    time: "۱:۲۸:۰۰",
    rate: "۹۸٪",
    description:
      "در یک دنیایی که اسباب‌بازی‌ها در غیاب انسان‌ها زنده می‌شوند. گروهی از اسباب‌بازی‌ها درحال آماده شدن برای نقل مکان به یک خانه جدید به همراه صاحبشان ...",
  },
  // Luca
  {
    id: 9,
    url: "./images/animation/luca.svg",
    name: "لوکا",
    year: "۲۰۲۱",
    category: "انیمیشن",
    bgImg: "../images/animation/luca.svg",
    image1: "../images/D-Animation/luca1.jpg",
    image2: "../images/D-Animation/luca2.jpg",
    image3: "../images/D-Animation/luca3.jpg",
    age: "+۳",
    time: "۱:۳۵:۰۰",
    rate: "۷۸٪",
    description:
      "کودک هیولای دریایی ترسو، لوکا پاگورو، از چند بزماهی در سواحل شهر پورتوروسو در ایتالیا نگهداری می‌کند. والدینش از ترس اینکه ممکن است توسط انسان‌ها شکار شود ...",
  },
  // Soul
  {
    id: 10,
    url: "./images/animation/soul.svg",
    name: "روح",
    year: "۲۰۲۰",
    category: "انیمیشن",
    bgImg: "../images/animation/soul.jpg",
    image1: "../images/D-Animation/soul1.jpg",
    image2: "../images/D-Animation/soul2.jpg",
    image3: "../images/D-Animation/soul3.jpg",
    age: "+۳",
    time: "۲:۳۸:۰۰",
    rate: "۵۸٪",
    description:
      "داستان فیلم پویانمایی روح، دربارهٔ جو گاردنر، آموزگار نوازندگی یک گروه موسیقی در دبیرستان است. جو که همیشه سودای اجرای موسیقی جاز بر صحنه را در سر می‌پرورانده ...",
  },
  // Rango
  {
    id: 11,
    url: "./images/animation/rango.svg",
    name: "رنگو",
    year: "۲۰۱۱",
    category: "انیمیشن",
    bgImg: "../images/animation/sponge-bob.png",
    image1: "../images/D-Animation/ablagh1.jpg",
    image2: "../images/D-Animation/ablagh2.jpg",
    image3: "../images/D-Animation/ablagh3.jpg",
    age: "+۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۱۸٪",
    description:
      "راحله به همراه خوانواده در یکی از محله‌های تهران زندگی می‌کنند. شوهر خواهر علی، فردی است که یک کسب و کار را برای خانم‌های محله ایجاد کرده است.",
  },
  // Dolphin Boy
  {
    id: 12,
    url: "./images/animation/dolphin.svg",
    name: "پسر دلفینی",
    year: "۲۰۲۱",
    category: "انیمیشن",
    bgImg: "../images/animation/sponge-bob.png",
    image1: "../images/D-Animation/ablagh1.jpg",
    image2: "../images/D-Animation/ablagh2.jpg",
    image3: "../images/D-Animation/ablagh3.jpg",
    age: "+۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۱۸٪",
    description:
      "راحله به همراه خوانواده در یکی از محله‌های تهران زندگی می‌کنند. شوهر خواهر علی، فردی است که یک کسب و کار را برای خانم‌های محله ایجاد کرده است.",
  },
  // Turning Red
  {
    id: 13,
    url: "./images/animation/turning-red.svg",
    name: "قرمز شدن",
    year: "۲۰۲۱",
    category: "انیمیشن",
    bgImg: "../images/animation/sponge-bob.png",
    image1: "../images/D-Animation/ablagh1.jpg",
    image2: "../images/D-Animation/ablagh2.jpg",
    image3: "../images/D-Animation/ablagh3.jpg",
    age: "+۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۱۸٪",
    description:
      "راحله به همراه خوانواده در یکی از محله‌های تهران زندگی می‌کنند. شوهر خواهر علی، فردی است که یک کسب و کار را برای خانم‌های محله ایجاد کرده است.",
  },
];
export default AnimationsArr;
