const MainMovie = [
  {
    id: 42,
    url: "./images/GharibFilm.png",
    urlMobile: "./images/Main-Movies/Gharib-480.jpg",
    name: "غریب",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "../images/mainMovies/gharib1.jpg",
    image2: "../images/mainMovies/gharib2.jpg",
    image3: "../images/mainMovies/gharib3.jpg",
    age: "+۱۲",
    time: "۲:۰۸:۰۰",
    rate: "۸۸٪",
    bgImg: "../gharib.jpg",
    description:
      "با آغاز شورش کردها در ایران توسط احزاب کُرد در سال ۱۳۵۸ از جمله کومله و دموکرات، محمد بروجردی از طرف آیت الله خمینی مأموریت می‌یابد تا ...",
    text: "داستان با آغاز شورش کردها در ایران توسط احزاب کُرد در سال ۱۳۵۸ از جمله کومله و دموکرات، محمد بروجردی از طرف آیت الله خمینی مأموریت می‌یابد تا به‌عنوان فرمانده سپاه پاسداران انقلاب اسلامی در کردستان وضعیت را به حالت عادی برگرداند...",
    save: "../images/Watch/save.svg",
    saved: "../images/Watch/saved.svg",
  },
  {
    id: 43,
    url: "./images/Main-Movies/maghz.jpg",
    urlMobile: "./images/Main-Movies/Maqz-480.jpg",
    name: "مغزهای کوچک زنگ زده",
    category: "فیلم",
    year: "۱۳۹۷",
    image1: "../images/Main-Movies/maghz-1.png",
    image2: "../images/Main-Movies/maghz-2.png",
    image3: "../images/Main-Movies/maghz-3.png",
    age: "+۱۳",
    time: "۱:۴۲:۰۰",
    rate: "۹۲٪",
    bgImg: "../images/Main-Movies/maghzbg.png",
    description:
      "در منطقه ای نزدیک البرز و زندان قزل حصار، یک آبادی وجود دارد که مختص فقیران و آشغال جمع کن‌ها، اراذل و اوباش، فروشندگان مواد و افراد به شدت گیر افتاده در تمکن مالی است.",
    text: "در منطقه ای نزدیک البرز و زندان قزل حصار، یک آبادی وجود دارد که مختص فقیران و آشغال جمع کن‌ها، اراذل و اوباش، فروشندگان مواد و افراد به شدت گیر افتاده در تمکن مالی است. شکور، شاهین، شهره و شهروز به همراه پدر و مادرشان، در این آبادی زندگی می‌کنند.",
    save: "../images/Watch/save.svg",
    saved: "../images/Watch/saved.svg",
  },
  {
    id: 44,
    url: "./images/Main-Movies/sorkh2.jpg",
    urlMobile: "./images/Main-Movies/Sorkh-480.jpg",
    name: "سرخ پوست",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "../images/Main-Movies/sorkh-1.png",
    image2: "../images/Main-Movies/sorkh-2.png",
    image3: "../images/Main-Movies/sorkh-3.png",
    age: "+۱۳",
    time: "۱:۴۰:۰۰",
    rate: "۸۷٪",
    bgImg: "../images/Main-Movies/sorkhbg.jpg",
    description:
      "سال ۱۳۴۶، یک زندان قدیمی در جنوب، به دلیل مجاورت با فرودگاهِ در حال توسعهٔ شهر، در حال تخلیه است. ",
    text: "سال ۱۳۴۶، یک زندان قدیمی در جنوب، به دلیل مجاورت با فرودگاهِ در حال توسعهٔ شهر، در حال تخلیه است. سرگرد نعمت جاهد (نوید محمدزاده)، رئیس زندان، به همراه مأمورانش در حال انتقال زندانیان به زندان جدید هستند و قرار است خود سرگرد به همراه افرادش تا عصر از زندان بروند.",
    save: "../images/Watch/save.svg",
    saved: "../images/Watch/saved.svg",
  },
  {
    id: 45,
    url: "./images/Main-Movies/metri6_2jpg.jpg",
    urlMobile: "./images/Main-Movies/Setare-480.jpg",
    name: "ستاره بازی",
    category: "فیلم",
    year: "۱۴۰۱",
    image1: "../images/Main-Movies/setarebazi-1.jpg",
    image2: "../images/Main-Movies/setarebazi-2.jpg",
    image3: "../images/Main-Movies/setarebazi-3.jpg",
    age: "+۱۶",
    time: "۱:۳۳:۰۰",
    rate: "۸۹٪",
    bgImg: "../images/Main-Movies/setarebazi.png",
    description:
      "ستاره بازی فیلمی به کارگردانی هاتف علیمردانی و تهیه‌کنندگی علی سرتیپی محصول سال ۱۳۹۸ است. این فیلم در سی و نهمین دوره جشنواره فیلم فجر حضور داشت.",
    text: "چند تن از مأمورین پلیس مبارزه با مواد مخدر به سردستگی صمد (پیمان معادی) به دنبال فروشندهٔ بزرگ شیشه در تهران به اسم ناصر خاکزاد (نوید محمدزاده) هستند. نام فیلم برگرفته از خاطرهٔ ناصر خاکزاد، متهم پروندهٔ مواد مخدر است که در بخشی از سکانس دادگاه روایت می‌کند که کفن برادرش را متری شش و نیم خریدند.",
    save: "../images/Watch/save.svg",
    saved: "../images/Watch/saved.svg",
  },
];
export default MainMovie;
