const OnlineMovie = [
  {
    id: 1,
    url: "/./images/CinemaOnline/ablagh.webp",
    name: "ابلق",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/../images/Watch/ablagh1.webp",
    image2: "/../images/Watch/ablagh2.webp",
    image3: "/../images/Watch/ablagh3.webp",
    age: "+۱۲",
    time: "۲:۳۸:۰۰",
    rate: "۱۸٪",
    bgImg: "../images/Watch/ablagh.webp",
    description:
      "راحله به همراه همسرش علی و دختر کوچکش در یکی از محله‌های حاشیه‌ای تهران زندگی می‌کنند...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  {
    id: 14,
    url: "/./images/CinemaOnline/worldwar3.webp",
    name: "جنگ جهانی سوم",
    category: "فیلم",
    year: "۱۴۰۱",
    image1: "/../images/Online/ww3-1.webp",
    image2: "/../images/Online/ww3-2.webp",
    image3: "/../images/Online/ww3-3.webp",
    age: "+۱۳",
    time: "۱:۴۷:۰۸",
    rate: "۶۷٪",
    bgImg: "../images/Online/ww3.webp",
    description:
      "شکیب (محسن تنابنده) یک کارگر روزمزد میانسالِ بی‌خانمان است که همسر و پسرش را سال‌ها پیش در زلزله از دست داده و تاکنون با این امر کنار نیامده است",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  {
    id: 15,
    url: "/./images/CinemaOnline/maslahat.webp",
    name: "مصلحت",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/../images/Online/maslahat1.webp",
    image2: "/../images/Online/maslahat2.webp",
    image3: "/../images/Online/maslahat3.webp",
    age: "+۱۶",
    time: "۲:۱۴:۰۰",
    rate: "۵۴٪",
    bgImg: "../images/Online/maslahat.webp",
    description:
      "داستان از آنجایی آغاز می‌شود که «مهدی» پسر آیت‌الله مشکاتیان که یکی از مقامات بلندپایه‌ی قوه‌ی قضائیه است، مرتکب قتل می‌شود، اما از پذیرفتن آن سر باز می‌زند و ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  {
    id: 16,
    url: "/./images/CinemaOnline/fosil.webp",
    name: "فسیل",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/../images/Online/fosil1.webp",
    image2: "/../images/Online/fosil2.webp",
    image3: "/../images/Online/fosil3.webp",
    age: "+۱۵",
    time: "۱:۵۰:۰۰",
    rate: "۹۷٪",
    bgImg: "../images/Online/fosil.webp",
    description:
      "اسماعیل، سعید و صفا که عضو گروه موسیقی بلک داگز هستند، برای معروفیت و موفقیت تلاش دارند. اسماعیل (با نام خوانندگی اسی) دنبال اجرا جلوی شاه است. اما ...",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
];

export default OnlineMovie;
