const FavoritesArr = [
  //ablagh
  {
    id: 1,
    url: "/images/favorites/Frame1.png",
    name: "ابلق",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/images/Watch/ablagh1.webp",
    image2: "/images/Watch/ablagh2.webp",
    image3: "/images/Watch/ablagh3.webp",
    age: "+۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۱۸٪",
    bgImg: "../images/Watch/ablagh.webp",
    description:
      "راحله به همراه خوانواده در یکی از محله‌های تهران زندگی می‌کنند. شوهر خواهر علی، فردی است که یک کسب و کار را برای خانم‌های محله ایجاد کرده است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //titi
  {
    id: 2,
    url: "/images/favorites/Frame2.webp",
    name: "تی تی",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/images/Watch/titi1.webp",
    image2: "/images/Watch/titi2.webp",
    image3: "/images/Watch/titi3.webp",
    age: "+۱۸",
    time: "۱:۴۲:۵۹",
    rate: "۶۵٪",
    bgImg: "../images/Watch/titi.webp",
    description:
      "ابراهیم، استاد فیزیک دانشگاه که روی تئوری پایان دنیا کار می‌کند، در بیمارستان با خانم نظافتچی عجیبی به نام تی تی آشنا می‌شود.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //posteshir
  {
    id: 3,
    url: "/images/favorites/Frame3.webp",
    name: "پوست شیر‍",
    category: "سریال",
    year: "۱۴۰۱",
    image1: "/images/Watch/frame1.webp",
    image2: "/images/Watch/frame2.webp",
    image3: "/images/Watch/frame3.webp",
    age: "+۱۴",
    time: "۴۵:۳۰",
    rate: "۹۰٪",
    bgImg: "../images/Watch/postshir.webp",
    description:
      "نعیم که پانزده سال زندان را به عشق دیدن دخترش تاب آورده پس از رهایی، برای دیدار با او دچار بحرانی بزرگ می شود.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //marde baznde
  {
    id: 4,
    url: "/images/favorites/Frame4.webp",
    name: "مرد بازنده",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "/images/Watch/loser1.webp",
    image2: "/images/Watch/loser2.webp",
    image3: "/images/Watch/loser3.webp",
    age: "+۱۵",
    time: "۱:۵۳:۳۰",
    rate: "۵۵٪",
    bgImg: "../images/Watch/loser.webp",
    description:
      "احمد خسروی مسئول رسیدگی به پرونده‌های مشکوک به قتل می‌شود و به سرنخ‌هایی دست می‌یابد که پشت پرده این قتل رازگونه به کشف شبکه فساد اقتصادی می‌رسد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //sag band
  {
    id: 5,
    url: "/images/favorites/Frame5.webp",
    name: "سگ بند",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "/images/Watch/sagband1.webp",
    image2: "/images/Watch/sagband2.webp",
    image3: "/images/Watch/sagband4.webp",
    age: "+۱۶",
    time: "۱:۳۰:۳۰",
    rate: "۹۸٪",
    bgImg: "../images/Watch/sagband.webp",
    description:
      "هیچ وقت گول اسم و ظاهر آدم‌ها رو نخورید؛ ارتش هیتلر با اون عظمت، اسمش نازی بود. این فیلم سینمایی  دومین ساخته مهران احمدی پس از فیلم سینمایی «مصادره» محسوب می‌شود.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //shadravan
  {
    id: 6,
    url: "/images/favorites/Frame6.webp",
    name: "شادروان",
    category: "فیلم",
    year: "۱۴۰۱",
    image1: "/images/Watch/shad1.webp",
    image2: "/images/Watch/shad2.webp",
    image3: "/images/Watch/shad3.webp",
    age: "+۱۷",
    time: "۱:۳۴:۳۰",
    rate: "۳۵٪",
    bgImg: "../images/Watch/shad.webp",
    description:
      "شادروان به دردسرهای یک خانواده پس از فوت ناگهانی پدرشان می‌پردازد. آن‌ها که در حاشیهٔ شهر زندگی می‌کنند و حالا با درگذشت پدرشان ماجراهای تازه‌ای برایشان به وجود می‌آید.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //zelava
  {
    id: 7,
    url: "/images/favorites/Frame7.webp",
    name: "زالاوا",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/images/Watch/zelava1.webp",
    image2: "/images/Watch/zelava2.webp",
    image3: "/images/Watch/zelava3.webp",
    age: "+۱۳",
    time: "۱:۳۰:۱۵",
    rate: "۴۵٪",
    bgImg: "../images/Watch/zelava.webp",
    description:
      "داستان زالاوا در اواخر دههٔ ۱۳۵۰ خورشیدی روی می‌دهد و راوی اتفاقی است که باعث ترس مردم شده و رئیس پاسگاه تلاش می‌کند تا امنیت را به روستا بازگرداند.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //last of us
  {
    id: 8,
    url: "/images/favorites/Frame8.webp",
    name: "The Last of Us",
    category: "سریال",
    year: "۲۰۱۳",
    image1: "/images/Watch/last1.webp",
    image2: "/images/Watch/last2.webp",
    image3: "/images/Watch/last3.webp",
    age: "+۱۴",
    time: "۴۶:۲۰",
    rate: "۸۷٪",
    bgImg: "../images/favorites/Frame8.webp",
    description:
      "وقایع این سریال در سال ۲۰۲۳ جریان دارد و اتفاقات مربوط به ۲۰ سال پس از همه‌گیری یک بیماری قارچی را به تصویر می‌کشد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //bedon gharar ghabli
  {
    id: 9,
    url: "/images/favorites/Frame9.webp",
    name: "بدون قرار قبلی",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "/images/Watch/gharar4.webp",
    image2: "/images/Watch/gharar5.webp",
    image3: "/images/Watch/gharar6.webp",
    age: "+۱۵",
    time: "۲:۰۲:۰۵",
    rate: "۵۸٪",
    bgImg: "../images/Watch/gharar.webp",
    description:
      "داستان فیلم در مورد دختری به نام یاسمن است که پس از سال‌ها به دلیل مرگ پدرش از آلمان به ایران بازگشته است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //john wick 4
  {
    id: 10,
    url: "/images/Watch/john-wick.webp",
    name: "John Wick: Chapter 4",
    category: "فیلم",
    year: "۲۰۲۳",
    image1: "/images/Watch/john-wick1.webp",
    image2: "/images/Watch/john-wick2.webp",
    image3: "/images/Watch/john-wick3.webp",
    age: "+۱۵",
    time: "۲:۴۹:۱۵",
    rate: "۹۲٪",
    bgImg: "../images/Watch/john-wick.webp",
    description:
      "چند سالی است که ماشینش را دزدیده و سگش را کشته‌اند و صدها نفر کشته شده‌اند. جان ویک هر قانون ممکنی در دنیای زیرزمینی قاتلان شکسته.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //shenaye parvane
  {
    id: 11,
    url: "/images/favorites/Frame11.webp",
    name: "شنای پروانه",
    category: "فیلم",
    year: "۱۳۹۸",
    image1: "/images/Watch/shena1.webp",
    image2: "/images/Watch/shena2.webp",
    image3: "/images/Watch/shena3.webp",
    age: "+۱۵",
    time: "۲:۰۱:۱۷",
    rate: "۶۷٪",
    bgImg: "../images/Watch/shena.webp",
    description:
      "پروانه به گاراژ صافکاری برادرشوهرش حجت می‌رود و از او می‌خواهد تا جلوی همسرش هاشم  را بگیرد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //mogheiat mahdi
  {
    id: 12,
    url: "/images/favorites/Frame12.webp",
    name: "موقعیت مهدی",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "/images/Watch/mehdi1.webp",
    image2: "/images/Watch/mehdi2.webp",
    image3: "/images/Watch/mehdi3.webp",
    age: "+۱۵",
    time: "۱:۴۰:۰۰",
    rate: "۷۵٪",
    bgImg: "../images/Watch/mehdi.webp",
    description:
      "داستان درباره زندگی مهدی باکری و رابطه وی با همسرش، شرکت در جنگ ایران و عراق همراه برادرش حمید باکری، فرماندهی سپاه عاشورا در جنگ و به شهادت رسیدن وی است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  //dozist
  {
    id: 13,
    url: "/images/favorites/Frame13.webp",
    name: "دوزیست",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "/images/Watch/dozist1.webp",
    image2: "/images/Watch/dozist2.webp",
    image3: "/images/Watch/dozist3.webp",
    age: "+۱۵",
    time: "۱:۳۵:۰۰",
    rate: "۶۹٪",
    bgImg: "../images/Watch/dozist.webp",
    description:
      "در جنوب شهر، پسری به نام عطا (جواد عزتی)، با پدرش زندگی می‌کند و دو تن از دوستان خود را نیز به خانه راه داده‌ است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
];

export default FavoritesArr;
