const FavoritesArr = [
  //ablagh
  {
    id: 1,
    url: "./images/favorites/Frame1.png",
    name: "ابلق",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "../images/Watch/ablagh1.jpg",
    image2: "../images/Watch/ablagh2.jpg",
    image3: "../images/Watch/ablagh3.jpg",
    age: "۱۳",
    time: "۲:۳۸:۰۰",
    rate: "۱۸",
    bgImg: "../images/Watch/ablagh.svg",
  },
  //titi
  {
    id: 2,
    url: "./images/favorites/frame2.png",
    name: "تی تی",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "../images/Watch/titi1.png",
    image2: "../images/Watch/titi2.jpg",
    image3: "../images/Watch/titi3.png",
    age: "۱۸",
    time: "۱:۴۲:۵۹",
    rate: "۶۵",
    bgImg: "../images/Watch/titi.svg",
  },
  //posteshir
  {
    id: 3,
    url: "./images/favorites/Frame3.png",
    name: "پوست شیر‍",
    category: "سریال",
    year: "۱۴۰۱",
    image1: "../images/Watch/frame1.svg",
    image2: "../images/Watch/frame2.svg",
    image3: "../images/Watch/frame3.svg",
    age: "۱۴",
    time: "۴۵:۳۰",
    rate: "۹۰",
    bgImg: "../images/Watch/postshir.svg",
  },
  //marde baznde
  {
    id: 4,
    url: "./images/favorites/Frame4.png",
    name: "مرد بازنده",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "../images/Watch/loser1.jpg",
    image2: "../images/Watch/loser2.jpg",
    image3: "../images/Watch/loser3.jpg",
    age: "۱۵",
    time: "۱:۵۳:۳۰",
    rate: "۵۵",
    bgImg: "../images/Watch/loser.svg",
  },
  //sag band
  {
    id: 5,
    url: "./images/favorites/Frame5.png",
    name: "سگ بند",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "../images/Watch/sagband1.jpg",
    image2: "../images/Watch/sagband2.jpg",
    image3: "../images/Watch/sagband4.jpg",
    age: "۱۶",
    time: "۱:۳۰:۳۰",
    rate: "۲۴",
    bgImg: "../images/Watch/sagband.svg",
  },
  //shadravan
  {
    id: 6,
    url: "./images/favorites/Frame6.png",
    name: "شادروان",
    category: "فیلم",
    year: "۱۴۰۱",
    image1: "../images/Watch/shad1.jpg",
    image2: "../images/Watch/shad2.jpg",
    image3: "../images/Watch/shad3.jpg",
    age: "۱۷",
    time: "۱:۳۴:۳۰",
    rate: "۳۵",
    bgImg: "../images/Watch/shad.svg",
  },
  //zelava
  {
    id: 7,
    url: "./images/favorites/Frame7.jpg",
    name: "زلاوا",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "../images/Watch/zelava1.jpg",
    image2: "../images/Watch/zelava2.jpg",
    image3: "../images/Watch/zelava3.png",
    age: "۱۳",
    time: "۱:۳۰:۱۵",
    rate: "۴۵",
    bgImg: "../images/Watch/zelava.svg",
  },
  //last of us
  {
    id: 8,
    url: "./images/favorites/Frame8.jpg",
    name: "The Last of Us",
    category: "سریال",
    year: "۲۰۱۳",
    image1: "../images/Watch/last1.jpg",
    image2: "../images/Watch/last2.jpg",
    image3: "../images/Watch/last3.jpg",
    age: "۱۴",
    time: "۴۶:۲۰",
    rate: "۸۷",
    bgImg: "../images/favorites/Frame8.jpg",
  },
  //bedon gharar ghabli
  {
    id: 9,
    url: "./images/favorites/Frame9.jpg",
    name: "بدون قرار قبلی",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "../images/Watch/gharar4.jpg",
    image2: "../images/Watch/gharar5.jpg",
    image3: "../images/Watch/gharar6.jpg",
    age: "۱۵",
    time: "۲:۰۲:۰۵",
    rate: "۵۸",
    bgImg: "../images/Watch/gharar.svg",
  },
  //john wick 4
  {
    id: 10,
    url: "../images/Watch/john-wick.svg",
    name: "John Wick: Chapter 4",
    category: "فیلم",
    year: "۲۰۲۳",
    image1: "../images/Watch/john-wick1.png",
    image2: "../images/Watch/john-wick2.png",
    image3: "../images/Watch/john-wick3.png",
    age: "۱۵",
    time: "۲:۴۹:۱۵",
    rate: "۹۲",
    bgImg: "../images/Watch/john-wick.svg",
  },
  //shenaye parvane
  {
    id: 11,
    url: "./images/favorites/Frame11.jpg",
    name: "شنای پروانه",
    category: "فیلم",
    year: "۱۳۹۸",
    image1: "../images/Watch/shena1.jpg",
    image2: "../images/Watch/shena2.png",
    image3: "../images/Watch/shena3.jpg",
    age: "۱۵",
    time: "۲:۰۱:۱۷",
    rate: "۶۷",
    bgImg: "../images/Watch/shena.svg",
  },
  //mogheiat mahdi
  {
    id: 12,
    url: "./images/favorites/Frame12.jpeg",
    name: "موقعیت مهدی",
    category: "فیلم",
    year: "۱۴۰۰",
    image1: "../images/Watch/mehdi1.png",
    image2: "../images/Watch/mehdi2.jpg",
    image3: "../images/Watch/mehdi3.jpg",
    age: "۱۵",
    time: "۱:۴۰:۰۰",
    rate: "۷۵",
    bgImg: "../images/Watch/mehdi.svg",
  },
  //dozist
  {
    id: 13,
    url: "./images/favorites/Frame13.jpg",
    name: "دوزیست",
    category: "فیلم",
    year: "۱۳۹۹",
    image1: "../images/Watch/dozist1.jpg",
    image2: "../images/Watch/dozist2.jpg",
    image3: "../images/Watch/dozist3.jpg",
    age: "۱۵",
    time: "۱:۳۵:۰۰",
    rate: "۶۹",
    bgImg: "../images/Watch/dozist.svg",
  },
];

export default FavoritesArr;
