const ExclusiveArr = [
  // Sedato
  {
    id: 17,
    url: "/./images/exclusive/sedato.png",
    urlMobile: "/./images/exclusive/sedato.png",
    name: "صداتو",
    date: "پنجشنبه‌ها",
    category: "ریلیتی‌شو",
    year: "۱۴۰۲",
    image1: "/../images/D-Exclusive/sedato1.webp",
    image2: "/../images/D-Exclusive/sedato4.webp",
    image3: "/../images/D-Exclusive/sedato3.webp",
    age: "+۳",
    time: "۴۵:۰۰",
    rate: "۶۲٪",
    bgImg: "../images/exclusive/sedato.png",
    description:
      "«صداتو» یک مسابقه موزیکال-معمایی به کارگردانی و تهیه‌کنندگی حامد جوادزاده و با اجرای محسن کیایی محصول سال ۱۴۰۲ می‌باشد که برای پلتفرم نمایش‌خوانگی فیلیمو ساخته شد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Actor
  {
    id: 18,
    url: "/./images/exclusive/actor.png",
    urlMobile: "/./images/exclusive/actor.png",
    name: "آکتور",
    date: "شنبه‌ها",
    category: "سریال",
    year: "۱۴۰۱",
    image1: "/../images/D-Exclusive/actorpng.webp",
    image2: "/../images/D-Exclusive/actor1.webp",
    image3: "/../images/D-Exclusive/actor2.webp",
    age: "+۱۳",
    time: "۴۲:۰۰",
    rate: "۸۹٪",
    bgImg: "../images/D-Exclusive/actor.webp",
    description:
      "داستان این سریال، درباره زندگی پر فراز و نشیب چند بازیگر مستعد تئاتر است که بعد از پیشنهادی که به آن‌ها می‌شود زندگی‌ شان درگیر ماجراهایی پیچیده می‌شود.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // The God Father
  {
    id: 19,
    url: "/./images/exclusive/godfather.png",
    urlMobile: "/./images/exclusive/godfather.png",
    name: "پدر خوانده",
    date: "جمعه‌ها",
    category: "ریلیتی‌شو",
    year: "۱۴۰۰",
    image1: "/../images/D-Exclusive/pedar1.webp",
    image2: "/../images/D-Exclusive/pedar2.webp",
    image3: "/../images/D-Exclusive/pedar3.webp",
    age: "+۱۳",
    time: "۵۷:۰۰",
    rate: "۷۸٪",
    bgImg: "../images/D-Exclusive/pedar.webp",
    description:
      "یک مجموعه نمایش خانگی ایرانی به کارگردانی سعید ابوطالب و محمدرضا رضائیان است که بر اساس بازی مافیا ساخته شده‌است.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
  // Nato
  {
    id: 20,
    url: "/./images/exclusive/nato.png",
    urlMobile: "/./images/D-Exclusive/nato-480.webp",
    name: "ناتو",
    date: "دوشنبه‌ها",
    category: "ریلیتی‌شو",
    year: "۱۴۰۲",
    image1: "/../images/D-Exclusive/nato1.webp",
    image2: "/../images/D-Exclusive/nato2.webp",
    image3: "/../images/D-Exclusive/nato3.webp",
    age: "+۱۳",
    time: "۵۳:۰۰",
    rate: "۷۶٪",
    bgImg: "../images/D-Exclusive/nato.webp",
    description:
      "ناتو سریال، برنامه، مسابقه یا رئالیتی شو جدید نمایش خانگی است که جایگزین فصل اول پدرخوانده است. سریال یا برنامه ناتو به صورت هفتگی برای دانلود قرار می گیرد.",
    save: "/../images/Watch/save.svg",
    saved: "/../images/Watch/saved.svg",
  },
];

export default ExclusiveArr;
